Numpy stands for Numerical Python. It is a python library-meaning it is not built into Python by default. You have to install it and use import to use it. 

Numpy gives you one main thing- a data structure called ndarray(n-dimensional array)- and hundreds of mathematical functions to work with it.

Think of Numpy as a supercharged version of a Python List-designed specifically for numbers and mathematical operations.

In [194]:
#What is an Array
#An array is a collection of elements — just like a list. But unlike a list:
#All elements must be the same data type
#Elements are stored side by side in memory — not scattered
#You can do math on the whole array at once — no loop needed

#Python List
prices=[85000,67000,56000,90000,75000]

#Numpy Array
import numpy as np
prices=np.array([85000,25000,65000,76000])

Why Do We Need NumPy-
In data analytics you work with thousands or millions of numbers. Doing math on them with regular Python is slow and verbose.

In [195]:
#Task- apply 10% discount to 5 product prices
prices=[85000,67000,56000,90000,75000]
discounted=[]

for i in prices:
    discount=i*0.1
    discounted.append(discount)
print(discounted)

[8500.0, 6700.0, 5600.0, 9000.0, 7500.0]


In [196]:
#using numpy - one line no loop
import numpy as np

prices=np.array([85000.5,67000.0,56000.0,90000,75000])
discounted=prices*0.1
print(discounted)

[8500.05 6700.   5600.   9000.   7500.  ]


Rules and Properties of Numpy-

1. All elements must be the same data type-unlike lists which can mix strings,ints,booleans.
2. Size is fixed after creation-you cannot append to a Numpy array like a list. You have to create a new one.
3. Operations apply to every element automatically-no loops needed
4. Faster and more memory efficient than Python lists -especially for large data.
5. Shape describes dimensions -(5,) means 1D with 5 elements. (3,4) means 2D with 3 rows and 4 columns

The ndarray- Memory layout

what is ndarray?
ndarray stands for n-dimensional array. The n means it can have any number
of dimensions:

| Dimensions | Name | Example |
|---|---|---|
| 1D | Vector | A single row of prices |
| 2D | Matrix | A table of sales — rows are products, columns are months |
| 3D | Tensor | Multiple tables — like monthly sales across multiple years |


In [197]:
#List
mixed=[8500,"laptop",5.6,True]

#numpy- same type enforced
arr=np.array([85000,25000,45000])
print(arr.dtype)
print(arr)

arr1=np.array([85000,25000.5,45000])
print(arr1.dtype)

arr2=np.array([85000,"tree",45000])
print(arr2.dtype) #U21 - everything converted to string
print(arr2)

arr3=np.array([85000,True,45000,"top"]) #True=1 ,False =0
print(arr3.dtype)
print(arr3)

arr4=np.array([85000.0,True,45000,"top"])
print(arr4.dtype)
print(arr4)

int64
[85000 25000 45000]
float64
<U21
['85000' 'tree' '45000']
<U21
['85000' 'True' '45000' 'top']
<U32
['85000.0' 'True' '45000' 'top']


In [198]:
#Key Attributes of ndarray
#every numpy array has these built in properties

prices=np.array([34500,78000,7600,5600,7800])

print(prices.dtype) #datatype
print(prices.shape) #dimension of the array - 5 elements,1 row
print(prices.ndim) #number of dimensions
print(prices.size) #total number of elements


int64
(5,)
1
5


| Attribute | What it tells you | Example output |
|---|---|---|
| .dtype | Data type of elements | int64, float64, <U21 |
| .shape | Dimensions as tuple | (5,) or (3, 4) |
| .ndim | Number of dimensions | 1 or 2 |
| .size | Total number of elements | 5 or 12 |

In [199]:
#1D array - 1 dimensional array
#1 row of values

prices=np.array([34500,78000,7600,5600,7800])

print(prices.dtype)
print(prices.shape) 
print(prices.ndim)
print(prices.size)

int64
(5,)
1
5


In [200]:
#2D Array - rows and columns- like a table
sales=np.array([[120,135,165],
                [580,560,340],
                [567,450,134]])

print(sales.dtype) 
print(sales.shape) #rows,columns
print(sales.ndim) #number of dimension
print(sales.size) #total elements
print(sales)

int64
(3, 3)
2
9
[[120 135 165]
 [580 560 340]
 [567 450 134]]


In [201]:
#1D array -
prices=np.array([34500,78000,7600,5600,7800])

print(prices[0])
print(prices[4])
print(prices[:])
print(prices[0:2])
print(prices[::-1])

34500
7800
[34500 78000  7600  5600  7800]
[34500 78000]
[ 7800  5600  7600 78000 34500]


In [202]:
#Indexing,accessing the elements

#2D array - 
sales=np.array([[120,135,165],
                [580,560,340],
                [567,450,134]])

print(sales[0,0]) #row 0 col 0
print(sales[2,0]) #row 2 col 0
print(sales[:,0]) #full col 0
print(sales[1,:]) #full 1st row
print(sales[1,::-1]) 
print(sales[1,:2])
print(sales[:,::2]) #evey 2nd column

120
567
[120 580 567]
[580 560 340]
[340 560 580]
[580 560]
[[120 165]
 [580 340]
 [567 134]]


In [203]:
import sys
print (sys.executable)
!{sys.executable} -m pip install numpy

c:\Users\Anand\AppData\Local\Python\pythoncore-3.14-64\python.exe



[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [204]:
#creating arrays

#creating 1D array
import numpy as np

prices=np.array([34500,78000,7600,5600,7800])
print(prices)

#creating 2D array
sales=np.array([[120,135,165],
                [580,560,340],
                [567,450,134]])

print(sales)

prices_float=np.array([34500.67,7800.67,7600.34,5600.64,78005],dtype=int)
print(prices_float)
print(prices_float.dtype)
prices_int=np.array([34500,78000,7600,5600,7800],dtype=float)
print(prices_int)
print(prices_int.dtype)

[34500 78000  7600  5600  7800]
[[120 135 165]
 [580 560 340]
 [567 450 134]]
[34500  7800  7600  5600 78005]
int64
[34500. 78000.  7600.  5600.  7800.]
float64


In [205]:
#Array filled with zeroes

#Creates an array where every element filled is zero.
#Used when u want to set up an empty result container before filling it

#1D Array
#Zeroes are float by default
placeholder=np.zeros(5) #5 zeroes
print(placeholder)
placeholder[0]=15
placeholder[4]=12
print(placeholder)
print(placeholder.dtype)

#2D Array
placeholder=np.zeros((3,2)) #shape-(rows,columns)
print(placeholder)
print(placeholder.dtype)


[0. 0. 0. 0. 0.]
[15.  0.  0.  0. 12.]
float64
[[0. 0.]
 [0. 0.]
 [0. 0.]]
float64


In [206]:
#np.ones - create an array filled with ones. on its own it is useless.
#but with certain situations it becomes useful.

#use cases-

#Create a starting array and multiply to any value.
#an array of same base price with multiple times
base_prices=np.ones(5)*1000
print(base_prices)

[1000. 1000. 1000. 1000. 1000.]


In [207]:
#equal weights for all products

weights=np.ones(5)/5
print(weights)

scores=np.array([85,90,76,92,88])
weighted_avg=np.sum(scores*weights)
print(weighted_avg)

[0.2 0.2 0.2 0.2 0.2]
86.20000000000002


In [208]:
#create an identity like array/table

sales_start=np.ones((3,4))
print(sales_start)

#multiple by growth rates
growth=np.array([100,120,90,110])
adjusted=sales_start*growth
print(adjusted)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[100. 120.  90. 110.]
 [100. 120.  90. 110.]
 [100. 120.  90. 110.]]


In [209]:
#adding the same curcharge on every product

prices=np.array([85000,25000,45000,5000,15000])
surcharge=np.ones(5)*500

print(prices)
print(surcharge)

final=prices+surcharge
print(final)

[85000 25000 45000  5000 15000]
[500. 500. 500. 500. 500.]
[85500. 25500. 45500.  5500. 15500.]


In [210]:
#np.arange - Sequence with a step
#Like python's range() but returns a numpy array and supports float steps

#syntax: np.arrange(start,stop,step)

#0 to 9
print(np.arange(10))

#month numbers
print(np.arange(1,13))

#with step-price tiers
print(np.arange(1000,11000,1000))

#with step- float
print(np.arange(0,1.1,0.1))

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1000  2000  3000  4000  5000  6000  7000  8000  9000 10000]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [211]:
#np.linspace -evenly spaced between two points

#syntax: np.linspace(start,stop,num)

#you tell it to start and stop and how many points you want
#It figures out the sapcing. Both start and stop are included

print(np.linspace(1000,11000,5))

[ 1000.  3500.  6000.  8500. 11000.]


In [212]:
#Vectorization
#Vectorization means performing an operation on an entire array at once instead of looping through each element one by one 

prices=[85000,25000,45000,5000,15000]

#without vectorization - loop is needed
discounted=[]
for i in prices:
    discounted.append(i*0.9)
print(discounted)

#with vectorization
prices=np.array([85000,25000,45000,5000,15000])
discounted=prices*0.9
print(discounted)

[76500.0, 22500.0, 40500.0, 4500.0, 13500.0]
[76500. 22500. 40500.  4500. 13500.]


In [213]:
#Why Vectorization is faster?
#python loops are interpreted line by line which is slow
#numpy skips the python interpreter for the actual math

import time
import numpy as np

#1 million prices
prices=np.array([100]*1000000)

#LOOP APPROACH
start=time.time()
result=[p*0.9 for p in prices]
end=time.time()
print(f"Loop: {end-start:.4f} Seconds")

#Vectorized approach
start=time.time()
result=prices*0.9
end=time.time()
print(f"Vectorized: {end-start:.4f} Seconds")

#Vectorized approach is roughly 87 times faster, the gap grows as data grows

Loop: 1.4295 Seconds
Vectorized: 0.0284 Seconds


In [214]:
#Arithmetic vectorization
prices=np.array([85000,25000,45000,5000,15000])

print(prices+5000)
print(prices-200)
print(prices*1.18)
print(prices/1000)
print(prices**2)

[90000 30000 50000 10000 20000]
[84800 24800 44800  4800 14800]
[100300.  29500.  53100.   5900.  17700.]
[85. 25. 45.  5. 15.]
[7225000000  625000000 2025000000   25000000  225000000]


In [215]:
#element-wise operations
#when you have two arrays of the same shape
prices=np.array([85000,25000,45000,5000,15000])
quantities=np.array([10,45,30,100,25])

revenue=prices*quantities
print(revenue)

[ 850000 1125000 1350000  500000  375000]


In [216]:
#Statstical operations
prices=np.array([85000,25000,45000,5000,15000])

print(np.sum(prices))
print(np.mean(prices))
print(np.median(prices))
print(np.max(prices))
print(np.min(prices))
print(np.std(prices)) #standard deviation-how spread out the values are

175000
35000.0
25000.0
85000
5000
28284.2712474619


In [ ]:
#Comparision operations
prices=np.array([85000,25000,45000,5000,15000])
print(prices>20000) #true or false
print(prices[prices>20000]) #filters out the data
print((prices>20000).sum()) #count the number of values meeting the condition

Total = prices[prices>20000]
print(np.sum(Total))
print(sum(Total))


[ True  True  True False False]
[85000 25000 45000]
3
155000
155000


### What is Broadcasting?
* Broadcasting is NumPy's ability to perform operations on arrays of different shapes — by automatically expanding the smaller array to match the larger one.
* Without broadcasting you could only do math between arrays of identical shapes. 
* Broadcasting removes that restriction.

In [218]:
#Scalar-single value based operation
prices=np.array([85000,25000,45000,5000,15000])
discount=0.9
#discount=[0.9,0.9,0.9,0.9,0.9] - internally it streches discount then multiply element-wise

result=prices*discount
print(result)

[76500. 22500. 40500.  4500. 13500.]


### Broadcasting Rules
* Python follows these three rules in order:
* Rule 1 — If arrays have different number of dimensions, the shape of the smaller one is padded with 1s on the left side.
* Rule 2 — Dimensions with size 1 are stretched to match the other array along that dimension.
* Rule 3 — If dimensions do not match and neither is 1 — ValueError. Cannot broadcas

In [219]:
#Broadcasting 1D array with 2D array

#Monthly sales- 3 products X 3 months

sales=np.array([[120,135,110], #laptop
                [200,180,220], #mobile
                [80,95,75]]) #tablet
print(sales.shape)

#Apply different growth rate to each month
growth=np.array([1.1,1.2,1.05])
print(growth.shape)

#Broadcasting -sales*growth
adjusted=sales*growth
print(adjusted)

(3, 3)
(3,)
[[132.   162.   115.5 ]
 [220.   216.   231.  ]
 [ 88.   114.    78.75]]


In [220]:
#3 Product sales across 3 months
import numpy as np
#2D array - product prices, months
sales = [[250,450,100], #phone
         [360,400,200], #laptop
         [150,170,300]] #keyboard
        #jan,feb,mar quantity sold
         
#product prices
prices=np.array([3000,4500,6000])
                #Phone price,laptop price,keyboard price

revenue=sales*prices
print(revenue)
print(revenue.shape)

[[ 750000 2025000  600000]
 [1080000 1800000 1200000]
 [ 450000  765000 1800000]]
(3, 3)


In [221]:
import numpy as np
#2D array - product prices, months
sales = np.array([[250,450,100], #phone #(3,3)
                  [360,400,200], #laptop 
                  [150,170,300]]) #keyboard
        #jan,feb,mar quantity sold

#product prices
prices=np.array([3000,4500,6000]) #(1,3)
                #Phone price,laptop price,keyboard price
revenue=sales*prices[:,np.newaxis] #npnewaxis - #(3,1)- to switch between dimensions
#np.newaxis is used to adjust the data for proper broadcasting
print(revenue)
print(revenue.shape)
print(prices)
print(prices.shape)
print(prices[:,np.newaxis])
print(prices[:,np.newaxis].shape)

#to change the dimension for rows
prices=np.array([3000,
                 4500,
                 6000]) #(3,1)
print(prices[np.newaxis,:])
print(prices[np.newaxis,:].shape)

[[ 750000 1350000  300000]
 [1620000 1800000  900000]
 [ 900000 1020000 1800000]]
(3, 3)
[3000 4500 6000]
(3,)
[[3000]
 [4500]
 [6000]]
(3, 1)
[[3000 4500 6000]]
(1, 3)


* to change the dimensions for rows 
    * 1row and 3columns 
        * print(prices[np.newaxis,:])

* to change the dimensions for columns 
    * 3rows and 1 column
        * print(prices[:,np.newaxis])

In [222]:
print(np.newaxis is None)

sales = np.array([[250,450,100], #phone #(3,3)
                  [360,400,200], #laptop
                  [150,170,300]]) #keyboard
                  #jan,feb,mar quantity sold


#product prices
prices=np.array([3000,4500,6000]) #(3,) - 3 rows,flat
                #Phone price,laptop price,keyboard price
print(prices.shape)
print(prices)
revenue=sales*prices[:,None] 
print(revenue)
print(revenue.shape)
print(prices[:,None])
print(prices[:,None].shape)


#to change the dimension for rows
prices=np.array([3000,
                 4500,
                 6000]) #(3,1)
print(prices[None,:])
print(prices[None,:].shape)

True
(3,)
[3000 4500 6000]
[[ 750000 1350000  300000]
 [1620000 1800000  900000]
 [ 900000 1020000 1800000]]
(3, 3)
[[3000]
 [4500]
 [6000]]
(3, 1)
[[3000 4500 6000]]
(1, 3)


3D Arrays: A 3D array is an array of 2D arrays. Think of it as a multiple tables stacked
| Dimensions | Think of it as |
|---|---|
| 1D | A single row — one product's prices |
| 2D | A table — products × months |
| 3D | Multiple tables — products × months × years |

In [223]:
import numpy as np

#sales data
#2 years, 3 products, 4 months

#Year 2023

year_2023=[[120,135,110,145], #laptop
           [200,180,220,190], #mobile
           [80,95,75,100]] #tablet
            #J  F  M  A

year_2024=[[150,160,140,170], #laptop
           [220,210,240,230], #mobilE
           [90,105,85,115]] #tablet
            #J  F  M  A

#Stak them into a 3D array
sales=np.array([year_2023,year_2024])

print(sales)
print(sales.shape) #(2,3,4) - 2 tables,3 rows,4 columns
print(sales.ndim) #3 - 3D
print(sales.size) #24 - total elements

[[[120 135 110 145]
  [200 180 220 190]
  [ 80  95  75 100]]

 [[150 160 140 170]
  [220 210 240 230]
  [ 90 105  85 115]]]
(2, 3, 4)
3
24


In [224]:
# 3D Dimension using Numpy style by mention the 2tables in a single bracket
sales=np.array([
                [
                [120,135,110,145],
                [200,180,220,190],
                [80,95,75,100]
                ],
            
                [
                [150,160,140,170], 
                [220,210,240,230],
                [90,105,85,115]
                ]
                ])
print(sales)
print(sales.shape)
print(sales.ndim)


[[[120 135 110 145]
  [200 180 220 190]
  [ 80  95  75 100]]

 [[150 160 140 170]
  [220 210 240 230]
  [ 90 105  85 115]]]
(2, 3, 4)
3


| Axis | Size | Represents |
|---|---|---|
| Axis 0 | 2 | Years |
| Axis 1 | 3 | Products |
| Axis 2 | 4 | Months |

In [225]:
#Indexing a 3D array
#Syntax:[Table,row,column]
#       [Year,Product,Month]

#Year 2023-entire table
print(sales[0])

#Year 2024-entire table
print(sales[1])

#Year 2023-laptop row
print(sales[0,0])

#Year 2024-mobile row
print(sales[1,1])

#Year 2023-laptop, February
print(sales[0,0,1])

#Year 2024-tablet, march
print(sales[1,2,2])

[[120 135 110 145]
 [200 180 220 190]
 [ 80  95  75 100]]
[[150 160 140 170]
 [220 210 240 230]
 [ 90 105  85 115]]
[120 135 110 145]
[220 210 240 230]
135
85


In [226]:
#Slicing a 3D array

#all years, laptop only, all months
print(sales[:,0,:])

#all years,all products,jan only
print(sales[:,:,0])

#year 2023,first 2 products,first 2 months
print(sales[0,:2,:2])

[[120 135 110 145]
 [150 160 140 170]]
[[120 200  80]
 [150 220  90]]
[[120 135]
 [200 180]]


In [227]:
#Operations on 3D arrays

#Apply 10% growth to all values
import numpy as np
print(sales*1.1)

#Total sales across everything
print(np.sum(sales))

#Total per year-sum across products and months
print(np.sum(sales,axis=(1,2)))

#Average per product across all years and months
print(np.average(sales,axis=(0,2)))


[[[132.  148.5 121.  159.5]
  [220.  198.  242.  209. ]
  [ 88.  104.5  82.5 110. ]]

 [[165.  176.  154.  187. ]
  [242.  231.  264.  253. ]
  [ 99.  115.5  93.5 126.5]]]
3565
[1650 1915]
[141.25  211.25   93.125]


In [ ]:
import numpy as np

# Q1 — np.array and attributes
prices     = [85000, 25000, 45000, 5000, 15000, 32000]
quantities = [10, 45, 30, 100, 25, 8]

# a. Convert both to NumPy arrays
prices = np.array([85000, 25000, 45000, 5000, 15000, 32000])
quantities = np.array([10, 45, 30, 100, 25, 8])
# b. Print dtype, shape, ndim, size of prices array
print(prices.dtype)
print(prices.shape)
print(prices.ndim)
print(prices.size)
# c. Access first and last price using indexing
print(prices[0])
print(prices[-1])
# d. Slice prices from index 1 to 4
print(prices[0:4])

# Q2 — 2D array
# Create this 2D array and answer:
# Rows: Laptop, Mobile, Tablet
# Columns: Jan, Feb, Mar sales
# Laptop:  120, 135, 110
# Mobile:  200, 180, 220
# Tablet:   80,  95,  75
sales=np.array([[120,135,110], #laptop
                [200,180,220], #mobile
                [80,95,75]]) #tablet
#                J  F  M
print(sales)

# a. Print dtype, shape, ndim, size
print(sales.dtype)
print(sales.shape) #rows,columns
print(sales.ndim) #number of dimension
print(sales.size) #total elements

# b. Access Mobile Feb sales (row 1, col 1)
print(sales[1,1])
# c. Print entire Tablet row
print(sales[2,:])
# d. Print entire Feb column
print(sales[:,1])

# Q3 — np.zeros and np.ones
# a. Create zeros array of shape (3, 4)
array_zeros=np.zeros((3,4))
print(array_zeros)
# b. Create ones array of 5 elements and multiply by 100
array_ones=np.ones(5)*100
print(array_ones)
prices=np.array([10,20,30,40,50])
print(prices)
multiplication=prices*array_ones
print(multiplication)
# c. Create zeros array of 6 elements
zero_array=np.zeros(6)
print(zero_array)
#    Fill positions 0, 2, 4 with 10, 20, 30
zero_array[0]=10
zero_array[2]=20
zero_array[4]=30
print(zero_array)

# Q4 — np.arange
# a. Months 1 to 12
months=np.arange(1,13)
print(months)
# b. Price tiers from 5000 to 50000 step 5000
price_tiers=np.arange(5000,50000,5000)
print(price_tiers)
# c. Discount percentages from 5% to 30% step 5%
discount_percentage=np.arange(0.05,0.3,0.05)
print(discount_percentage)
# d. Countdown from 10 to 1
countdown=np.arange(10,0,-1)
print(countdown)

# Q5 — np.linspace
# a. 5 evenly spaced prices between 1000 and 100000
prices=np.linspace(1000,100000,5)
print(prices)
# b. 4 evenly spaced discount rates between 0% and 30%
discount_rates=np.linspace(0,0.3,4)
print(discount_rates)
# c. 7 evenly spaced temperatures between 20 and 40 degrees
temperature=np.linspace(20,40,7)
print(temperature)

# Q6 — Vectorization
prices     = np.array([85000, 25000, 45000, 5000, 15000])
quantities = np.array([10, 45, 30, 100, 25])

# a. Apply 10% discount to all prices
discounted=prices*0.1
print(discounted)
# b. Add 18% GST to all prices
GST=(prices+prices*0.18)
print(GST)
# c. Calculate revenue —> prices × quantities
revenue=prices*quantities
print(revenue)
# d. Total, average, highest, lowest revenue
print(np.sum(revenue))
print(np.average(revenue))
print(np.mean(revenue))
print(np.max(revenue))
print(np.min(revenue))
# e. Which prices are above 20000 — print True/False array
print(prices>20000)
# f. Print only prices above 20000
print(prices[prices>20000])
# g. How many products are priced below 30000
print((prices<30000).sum())

# Q7 — Broadcasting
sales = np.array([
    [120, 135, 110],
    [200, 180, 220],
    [80,  95,  75]
])

# a. Multiply all sales by 1.1 — 10% growth for all
print(sales*1.1)

# b. Add 10 to every cell — 10 extra units across the board

# c. Monthly targets [130, 150, 120]
targets     = np.array([130, 150, 120])
performance = sales - targets
print(performance)

#    Subtract targets from sales — see over/under performance

# d. Price per product [85000, 25000, 45000]
prices_per_product = np.array([85000, 25000, 45000])
revenue            = sales * prices_per_product[:, np.newaxis]
print(revenue)

#    Calculate revenue for each product each month


int64
(6,)
1
6
85000
32000
[85000 25000 45000  5000]
[[120 135 110]
 [200 180 220]
 [ 80  95  75]]
int64
(3, 3)
2
9
180
[80 95 75]
[135 180  95]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[100. 100. 100. 100. 100.]
[10 20 30 40 50]
[1000. 2000. 3000. 4000. 5000.]
[0. 0. 0. 0. 0. 0.]
[10.  0. 20.  0. 30.  0.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 5000 10000 15000 20000 25000 30000 35000 40000 45000]
[0.05 0.1  0.15 0.2  0.25]
[10  9  8  7  6  5  4  3  2  1]
[  1000.  25750.  50500.  75250. 100000.]
[0.  0.1 0.2 0.3]
[20.         23.33333333 26.66666667 30.         33.33333333 36.66666667
 40.        ]
[8500. 2500. 4500.  500. 1500.]
[100300.  29500.  53100.   5900.  17700.]
[ 850000 1125000 1350000  500000  375000]
4200000
840000.0
840000.0
1350000
375000
[ True  True  True False False]
[85000 25000 45000]
3
[[132.  148.5 121. ]
 [220.  198.  242. ]
 [ 88.  104.5  82.5]]
